gpoPB = [{'nombre': 'Wesley Bennett', 'carrera': 'LSTI', 'sem': 2, 'mat': 2246073},
         {'nombre': 'Tamara Briggs', 'carrera': 'LA', 'sem': 2, 'mat': 1574446},
         {'nombre': 'Dr. Isaac Perez DVM', 'carrera': 'LA', 'sem': 2, 'mat': 1782989},
         {'nombre': 'Donald Evans', 'carrera': 'LF', 'sem': 2, 'mat': 2169976},
         {'nombre': 'Patty Romero', 'carrera': 'LA', 'sem': 2, 'mat': 2581409},
         {'nombre': 'Shelley Adams', 'carrera': 'LA', 'sem': 2, 'mat': 2081825},
         {'nombre': 'Melvin Pierce', 'carrera': 'LM', 'sem': 2, 'mat': 2326738},
         {'nombre': 'Robert King', 'carrera': 'LA', 'sem': 2, 'mat': 2110844},
         {'nombre': 'Grant Williams', 'carrera': 'LA', 'sem': 2, 'mat': 1572543},
         {'nombre': 'Tanya Santana', 'carrera': 'LM', 'sem': 2, 'mat': 2695234},
         {'nombre': 'Heidi Hunt', 'carrera': 'LA', 'sem': 2, 'mat': 2617152},
         {'nombre': 'Thomas Combs', 'carrera': 'LF', 'sem': 2, 'mat': 2602180},
         {'nombre': 'Destiny Rodriguez', 'carrera': 'LA', 'sem': 2, 'mat': 1829601},
         {'nombre': 'Steven Dixon', 'carrera': 'LA', 'sem': 2, 'mat': 2532473},
         {'nombre': 'Brooke Vega', 'carrera': 'LSTI', 'sem': 2, 'mat': 1728642},
         {'nombre': 'Kaitlyn Jordan', 'carrera': 'LMAD', 'sem': 2, 'mat': 1764674},
         {'nombre': 'Karen Burton', 'carrera': 'LCC', 'sem': 2, 'mat': 2076246},
         {'nombre': 'Mr. Jeffrey Weber', 'carrera': 'LMAD', 'sem': 2, 'mat': 2168054},
         {'nombre': 'Jeremy Phillips', 'carrera': 'LCC', 'sem': 2, 'mat': 2166005},
         {'nombre': 'Stephanie Hines', 'carrera': 'LMAD', 'sem': 2, 'mat': 2289836},
         {'nombre': 'Joseph Cortez', 'carrera': 'LCC', 'sem': 2, 'mat': 2145150},
         {'nombre': 'Greg Alexander', 'carrera': 'LMAD', 'sem': 2, 'mat': 1569366},
         {'nombre': 'Barbara Smith', 'carrera': 'LCC', 'sem': 2, 'mat': 1502357},
         {'nombre': 'Ralph Chung', 'carrera': 'LMAD', 'sem': 2, 'mat': 2364576},
         {'nombre': 'Brian Hendrix', 'carrera': 'LCC', 'sem': 2, 'mat': 2030406},
         {'nombre': 'Krista Chapman', 'carrera': 'LMAD', 'sem': 2, 'mat': 1830545},
         {'nombre': 'Allison Curry', 'carrera': 'LMAD', 'sem': 2, 'mat': 2716484},
         {'nombre': 'Christopher Stephens', 'carrera': 'LMAD', 'sem': 2, 'mat': 1623331},
         {'nombre': 'Nicole Garcia', 'carrera': 'LCC', 'sem': 2, 'mat': 2129392},
         {'nombre': 'Lori Gordon', 'carrera': 'LCC', 'sem': 2, 'mat': 2302760}
         ]

for alu in gpoPB:
    print(alu)
